name: level9 # you probably want to 'snapcraft register <name>'
version: '0.13' # just for humans, typically '1.2+git' or '1.3.2'
summary: Interpreter for Level 9 interactive fiction games # 79 char long summary
description: |
  Interpreter to play Level 9 Computing games.
  Files format accepted: .dat and .sna
  Save and restore are supported. Images works if picture files are present.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
 glklevel9:
    command: desktop-launch $SNAP/gtklevel9
    plugs: [x11, unity7, home]
    desktop: ./snap/gui/level9.desktop


parts:
 gtklevel9:
    # See 'snapcraft plugins'
    plugin: make
    source: ./code
    after: [desktop-gtk2]

 desktop-gtk2:
  source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  stage-packages:
   - light-themes
   - ttf-ubuntu-font-family
   - libgdk-pixbuf2.0-0
   - dmz-cursor-theme
   - shared-mime-info
